use_frameworks!

target 'KeyboardKit_Example' do
  pod 'KeyboardKit', :path => '../'
  
  target 'Keyboard' do
    pod 'KeyboardKit', :path => '../'
  end

  target 'KeyboardKit_Tests' do
    inherit! :search_paths
  end
end
